/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Accounts Endpoint
         * @description List all user accounts. Requires admin role.
         */
        get: operations["list_accounts_endpoint_api_v1_accounts_get"];
        put?: never;
        /**
         * Create Account Endpoint
         * @description Create a new user account. Requires admin role.
         */
        post: operations["create_account_endpoint_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Role Endpoint
         * @description Update a user's role. Requires admin role.
         */
        patch: operations["update_role_endpoint_api_v1_accounts__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/accounts/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password Endpoint
         * @description Reset a user's password. Requires admin role.
         */
        post: operations["reset_password_endpoint_api_v1_accounts__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account Endpoint
         * @description Delete a user account. Requires admin role.
         */
        delete: operations["delete_account_endpoint_api_v1_accounts__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user info.
         */
        get: operations["get_current_user_info_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Language
         * @description Update current user's language preference.
         */
        patch: operations["update_language_api_v1_me_language_patch"];
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Brands
         * @description Get paginated list of brands with optional search and marketplace filter.
         *
         *     Returns brands from VP data enriched with Meeting data when available.
         *     Supports pagination, case-insensitive brand name search, and marketplace filtering.
         */
        get: operations["list_brands_api_v1_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Brand
         * @description Get a single brand by ID with meeting data enrichment.
         */
        get: operations["get_brand_api_v1_brands__brand_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Features
         * @description Return current feature flags.
         */
        get: operations["get_features_api_v1_config_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List History Endpoint
         * @description List all email history with pagination and filtering.
         *
         *     Requires leader or admin role.
         */
        get: operations["list_history_endpoint_api_v1_email_history_get"];
        put?: never;
        post?: never;
        /**
         * Delete History Endpoint
         * @description Batch-delete email history entries. Requires admin role.
         */
        delete: operations["delete_history_endpoint_api_v1_email_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/history/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluation History Endpoint
         * @description List email history for a specific evaluation.
         *
         *     Requires leader or admin role.
         */
        get: operations["evaluation_history_endpoint_api_v1_email_history__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Email Endpoint
         * @description Send an evaluation report email.
         *
         *     Fetches evaluation data, renders the HTML template with the provided
         *     chart image, and sends (or previews in debug mode) the email.
         *     Logs the result to email_history.
         */
        post: operations["send_email_endpoint_api_v1_email_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/preview/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Email Endpoint
         * @description Preview the evaluation email as rendered HTML.
         *
         *     Returns the HTML that would be sent, with data URI images for browser
         *     rendering. Protected by authentication (no debug guard needed).
         *     Accepts an optional `language` query param to override the user's
         *     default language for the preview.
         */
        get: operations["preview_email_endpoint_api_v1_email_preview__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Evaluations Endpoint
         * @description List all evaluations with pagination and sorting.
         *
         *     Returns paginated evaluation history with brand names and evaluator emails.
         *     Only accessible by leaders and admins.
         *     Supports filtering by search (brand name) and date range (date_from, date_to).
         */
        get: operations["list_evaluations_endpoint_api_v1_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Grouped Evaluations Endpoint
         * @description List evaluations grouped by brand with pagination.
         *
         *     Returns brand-level summaries with evaluation count, top score, and latest date.
         *     Supports search by brand name and date range filter.
         */
        get: operations["list_grouped_evaluations_endpoint_api_v1_evaluations_grouped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/grouped/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Brand Evaluations Endpoint
         * @description List individual evaluations for a specific brand.
         *
         *     Returns evaluations sorted by date descending.
         *     Optional limit parameter for initial accordion expand (e.g., limit=5).
         */
        get: operations["list_brand_evaluations_endpoint_api_v1_evaluations_grouped__brand_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation Detail Endpoint
         * @description Get full details of a single evaluation by ID.
         */
        get: operations["get_evaluation_detail_endpoint_api_v1_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Evaluation Endpoint
         * @description Delete an evaluation permanently.
         *
         *     Only accessible by leaders and admins.
         *     Returns 204 on success, 404 if not found.
         */
        delete: operations["delete_evaluation_endpoint_api_v1_evaluations__evaluation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation
         * @description Get evaluation state for a brand.
         *
         *     Returns the shared evaluation inputs for this brand.
         *     If no inputs exist, returns the same shape with null values.
         */
        get: operations["get_evaluation_api_v1_evaluations_brands__brand_id__get"];
        /**
         * Update Evaluation
         * @description Save evaluation inputs for a brand.
         *
         *     Upserts the shared evaluation_inputs record for this brand.
         *     Records the current user as last_edited_by.
         *     Returns 404 if brand doesn't exist.
         */
        put: operations["update_evaluation_api_v1_evaluations_brands__brand_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calculator Results
         * @description Return all stored calculator results for a brand.
         *
         *     Returns an empty list if brand_id doesn't exist or has no results.
         *     This is intentional for read-only list endpoints (vs POST endpoints
         *     which validate brand existence and return 400).
         */
        get: operations["get_calculator_results_api_v1_evaluations_brands__brand_id__calculators_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/ads_keyword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Ads Keyword Calculator
         * @description Execute the Ads Keyword Calculator for a brand.
         *
         *     Loads required CSV data and manual inputs, runs the calculator,
         *     and stores the result. Returns 400 if required data is missing.
         */
        post: operations["run_ads_keyword_calculator_api_v1_evaluations_brands__brand_id__calculators_ads_keyword_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/discount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Discount Calculator
         * @description Execute the Discount Check Calculator for a brand.
         *
         *     Loads order export data, runs the calculator,
         *     and stores the result. Returns 400 if required data is missing.
         */
        post: operations["run_discount_calculator_api_v1_evaluations_brands__brand_id__calculators_discount_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/top_sku": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Top Sku Calculator
         * @description Execute the Top SKU Calculator for a brand.
         *
         *     Loads order export and mass update data, runs the calculator,
         *     and stores the result. Returns 400 if required data is missing.
         */
        post: operations["run_top_sku_calculator_api_v1_evaluations_brands__brand_id__calculators_top_sku_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/run-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run All Calculators
         * @description Run all calculators whose required files are available for a brand.
         *
         *     Returns per-calculator results (success, skipped, or error).
         */
        post: operations["run_all_calculators_api_v1_evaluations_brands__brand_id__calculators_run_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/calculators/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calculator Status
         * @description Return the readiness status of each calculator for a brand.
         */
        get: operations["get_calculator_status_api_v1_evaluations_brands__brand_id__calculators_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score Evaluation
         * @description Generate the final score for a brand evaluation.
         *
         *     Runs the scoring calculator with current manual inputs + calculator results.
         *     Returns the complete scoring result (scores, messages, email, whatsapp).
         *     Returns 400 if required data is missing.
         */
        post: operations["score_evaluation_api_v1_evaluations_brands__brand_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/brands/{brand_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Evaluation Endpoint
         * @description Save a completed evaluation as a permanent record.
         *
         *     Creates a new immutable evaluation record (INSERT-only).
         *     Multiple saves for the same brand create separate records (history).
         *     Returns 404 if brand doesn't exist, 422 if required fields are missing.
         */
        post: operations["save_evaluation_endpoint_api_v1_evaluations_brands__brand_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules
         * @description Get all scoring rules for a marketplace.
         *
         *     Requires leader or admin role.
         */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{template}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Rules Endpoint
         * @description Update scoring rules for a template and marketplace.
         *
         *     Requires leader or admin role.
         *     Password re-confirmation handled by frontend (Firebase reauthentication).
         */
        put: operations["update_rules_endpoint_api_v1_rules__template__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Trigger a manual sync of brand data.
         *
         *     Executes the sync synchronously and returns results when complete.
         *     Returns 409 if a sync is already in progress.
         */
        post: operations["trigger_sync_api_v1_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/eval-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Eval Sheet
         * @description Manually sync all evaluated brands to the Google Sheet.
         *
         *     Clears the sheet and repopulates with all brands that have evaluations.
         *     Only accessible by leaders and admins.
         */
        post: operations["sync_eval_sheet_api_v1_sync_eval_sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Status
         * @description Get the latest sync status.
         *
         *     Requires authentication. Returns the most recent sync operation's status
         *     including whether it succeeded, how many brands were synced, and any errors.
         */
        get: operations["get_sync_status_api_v1_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/signed-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Signed Url
         * @description Generate a GCS signed URL for direct file upload.
         */
        post: operations["create_signed_url_api_v1_upload_signed_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Processing
         * @description Process an uploaded file: download, parse, validate, store, auto-execute calculators.
         */
        post: operations["trigger_processing_api_v1_upload_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/brands/{brand_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploads
         * @description Return all uploaded files for a brand.
         */
        get: operations["get_uploads_api_v1_upload_brands__brand_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/brands/{brand_id}/download/{file_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description Generate a signed download URL for a previously uploaded file.
         */
        get: operations["download_file_api_v1_upload_brands__brand_id__download__file_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/local/{upload_id}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Local Download
         * @description Local dev endpoint: serve file bytes for download.
         *
         *     No auth required — mimics GCS signed URL behavior.
         */
        get: operations["local_download_api_v1_upload_local__upload_id___filename__get"];
        /**
         * Local Upload
         * @description Local dev endpoint: receive file bytes that would go to GCS in production.
         *
         *     No auth required — mimics GCS signed URL behavior where the URL itself
         *     is the authorization. The signed-url request that generated this URL
         *     was already authenticated.
         *
         *     Only available when gcs_upload_bucket is not configured.
         */
        put: operations["local_upload_api_v1_upload_local__upload_id___filename__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/sendgrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sendgrid Webhook
         * @description Receive SendGrid Event Webhook events and update email delivery status.
         */
        post: operations["sendgrid_webhook_api_v1_webhooks_sendgrid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check — verifies DB connectivity for Cloud Run readiness.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutoCalculatedItem */
        AutoCalculatedItem: {
            /** Calculator Type */
            calculator_type: string;
            /** Status */
            status: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * BrandDetailResponse
         * @description Single brand detail response.
         */
        BrandDetailResponse: {
            /** Id */
            id: number;
            /** Brand Name */
            brand_name: string;
            /** Raw Data */
            raw_data: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
            /** Meeting Raw Data */
            meeting_raw_data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BrandEvaluationItem
         * @description A single evaluation within a brand's evaluation list.
         */
        BrandEvaluationItem: {
            /** Id */
            id: number;
            /** Final Score */
            final_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /** Evaluator Email */
            evaluator_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Period
             * @default
             */
            period: string;
        };
        /**
         * BrandEvaluationListResponse
         * @description List of evaluations for a specific brand.
         */
        BrandEvaluationListResponse: {
            /** Items */
            items: components["schemas"]["BrandEvaluationItem"][];
            /** Total */
            total: number;
        };
        /**
         * BrandListItem
         * @description Individual brand item in paginated list.
         */
        BrandListItem: {
            /** Id */
            id: number;
            /** Brand Name */
            brand_name: string;
            /** Raw Data */
            raw_data: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
            /** Meeting Raw Data */
            meeting_raw_data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BrandListResponse
         * @description Paginated response for brand list.
         */
        BrandListResponse: {
            /** Items */
            items: components["schemas"]["BrandListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Pages */
            pages: number;
        };
        /**
         * BrandRawData
         * @description Extracted brand raw_data fields needed for email composition.
         */
        BrandRawData: {
            /** Email */
            email?: string | null;
            /** Pic Name */
            pic_name?: string | null;
            /** Store Link */
            store_link?: string | null;
            /** Kategori */
            kategori?: string | null;
        };
        /** BrandUploadsResponse */
        BrandUploadsResponse: {
            /** Brand Id */
            brand_id: number;
            /** Uploads */
            uploads: components["schemas"]["UploadResponse"][];
        };
        /**
         * CalculatorResultItem
         * @description A single stored calculator result.
         */
        CalculatorResultItem: {
            /** Calculator Type */
            calculator_type: string;
            /** Output Text */
            output_text: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
        };
        /**
         * CalculatorResultResponse
         * @description Response for calculator execution.
         */
        CalculatorResultResponse: {
            /** Calculator Type */
            calculator_type: string;
            /** Output Text */
            output_text: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
        };
        /**
         * CalculatorResultsListResponse
         * @description Response for fetching all stored calculator results for a brand.
         */
        CalculatorResultsListResponse: {
            /** Brand Id */
            brand_id: number;
            /** Results */
            results: components["schemas"]["CalculatorResultItem"][];
        };
        /**
         * CalculatorStatusResponse
         * @description Status of all calculators for a brand.
         */
        CalculatorStatusResponse: {
            /** Brand Id */
            brand_id: number;
            /** Calculators */
            calculators: {
                [key: string]: components["schemas"]["SingleCalculatorStatus"];
            };
        };
        /**
         * CategoryScoreItem
         * @description Per-category score breakdown.
         */
        CategoryScoreItem: {
            /** Category */
            category: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Rows */
            rows: components["schemas"]["RowScoreItem"][];
            /**
             * Available
             * @default true
             */
            available: boolean;
            category_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
        };
        /**
         * ColumnChangeDetail
         * @description Single header mismatch entry.
         */
        ColumnChangeDetail: {
            /** Position */
            position: number;
            /** Expected */
            expected?: string | null;
            /** Actual */
            actual?: string | null;
        };
        /**
         * CreateAccountRequest
         * @description Request body for creating a new account.
         */
        CreateAccountRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "member" | "leader" | "admin";
        };
        /**
         * DeleteEmailHistoryRequest
         * @description Request body for batch-deleting email history entries.
         */
        DeleteEmailHistoryRequest: {
            /** Ids */
            ids: number[];
        };
        /**
         * DeleteEmailHistoryResponse
         * @description Response after deleting email history entries.
         */
        DeleteEmailHistoryResponse: {
            /** Deleted */
            deleted: number;
        };
        /** DownloadResponse */
        DownloadResponse: {
            /** Download Url */
            download_url: string;
            /** Filename */
            filename: string;
        };
        /**
         * EmailHistoryItem
         * @description Single email history record.
         */
        EmailHistoryItem: {
            /** Id */
            id: number;
            /** Evaluation Id */
            evaluation_id: number;
            /** Sender Email */
            sender_email: string;
            /** Recipient Email */
            recipient_email: string;
            /** Cc Emails */
            cc_emails?: string[] | null;
            /** Bcc Emails */
            bcc_emails?: string[] | null;
            /** Subject */
            subject: string;
            /** Status */
            status: string;
            /** Message Id */
            message_id?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /**
         * EmailHistoryListResponse
         * @description Paginated email history response.
         */
        EmailHistoryListResponse: {
            /** Items */
            items: components["schemas"]["EmailHistoryItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Pages */
            pages: number;
        };
        /**
         * EvalSheetSyncResponse
         * @description Response model for eval sheet sync endpoint.
         */
        EvalSheetSyncResponse: {
            /** Success */
            success: boolean;
            /** Brands Synced */
            brands_synced: number;
            /** Error */
            error?: string | null;
        };
        /**
         * EvaluationDetailResponse
         * @description Full evaluation detail for the detail view page.
         */
        EvaluationDetailResponse: {
            /** Id */
            id: number;
            /** Brand Id */
            brand_id: number;
            /** Brand Name */
            brand_name: string;
            /** Final Score */
            final_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: unknown;
            }[];
            /** Calculator Results */
            calculator_results: {
                [key: string]: unknown;
            };
            /** Manual Inputs */
            manual_inputs: {
                [key: string]: unknown;
            };
            /** Email Output */
            email_output?: string | null;
            /** Evaluator Email */
            evaluator_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Rule Version */
            rule_version: number;
            /**
             * Period
             * @default
             */
            period: string;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
            brand_raw_data?: components["schemas"]["BrandRawData"];
        };
        /**
         * EvaluationInputsUpdate
         * @description Request body for saving evaluation inputs.
         */
        EvaluationInputsUpdate: {
            /** Category Type */
            category_type?: ("fashion" | "non_fashion") | null;
            /** Manual Data */
            manual_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
        };
        /**
         * EvaluationListItem
         * @description A single evaluation in the history list.
         */
        EvaluationListItem: {
            /** Id */
            id: number;
            /** Brand Name */
            brand_name: string;
            /** Final Score */
            final_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /** Evaluator Email */
            evaluator_email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Period
             * @default
             */
            period: string;
        };
        /**
         * EvaluationListResponse
         * @description Paginated list of evaluations.
         */
        EvaluationListResponse: {
            /** Items */
            items: components["schemas"]["EvaluationListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Pages */
            pages: number;
        };
        /**
         * EvaluationStateResponse
         * @description Current evaluation state for a brand+user pair.
         */
        EvaluationStateResponse: {
            /** Brand Id */
            brand_id: number;
            /** Category Type */
            category_type?: ("fashion" | "non_fashion") | null;
            /** Manual Data */
            manual_data?: {
                [key: string]: unknown;
            } | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * GroupedEvaluationItem
         * @description A single brand in the grouped evaluation list.
         */
        GroupedEvaluationItem: {
            /** Brand Id */
            brand_id: number;
            /** Brand Name */
            brand_name: string;
            /**
             * Marketplace
             * @default ID
             * @enum {string}
             */
            marketplace: "ID" | "TH";
            /** Evaluation Count */
            evaluation_count: number;
            /** Top Score */
            top_score: number;
            /**
             * Top Verdict
             * @enum {string}
             */
            top_verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Latest Date
             * Format: date-time
             */
            latest_date: string;
        };
        /**
         * GroupedEvaluationListResponse
         * @description Paginated list of evaluations grouped by brand.
         */
        GroupedEvaluationListResponse: {
            /** Items */
            items: components["schemas"]["GroupedEvaluationItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Pages */
            pages: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProcessRequest */
        ProcessRequest: {
            /** Upload Id */
            upload_id: string;
            /** Brand Id */
            brand_id: number;
            /** File Type */
            file_type: string;
        };
        /** ProcessUploadResponse */
        ProcessUploadResponse: {
            upload: components["schemas"]["UploadResponse"];
            /** Auto Calculated */
            auto_calculated: components["schemas"]["AutoCalculatedItem"][];
        };
        /**
         * ResetPasswordRequest
         * @description Request body for resetting a user's password.
         */
        ResetPasswordRequest: {
            /** Password */
            password: string;
        };
        /**
         * RowScoreItem
         * @description A single metric row score.
         */
        RowScoreItem: {
            /** Row */
            row: number;
            /** Metric */
            metric: string;
            /** Value */
            value: unknown;
            /** Benchmark */
            benchmark: string;
            /** Verdict */
            verdict: string;
            /** Message */
            message: string;
            /** Score */
            score: number;
            metric_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
            value_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
            message_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
            benchmark_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
        };
        /**
         * RunAllResponse
         * @description Response for run-all calculators endpoint.
         */
        RunAllResponse: {
            /** Results */
            results: components["schemas"]["RunCalculatorItem"][];
        };
        /**
         * RunCalculatorItem
         * @description Result of running a single calculator.
         */
        RunCalculatorItem: {
            /** Calculator Type */
            calculator_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "skipped" | "error";
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SaveEvaluationRequest
         * @description Request body for saving a completed evaluation as a permanent record.
         */
        SaveEvaluationRequest: {
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /** Final Score */
            final_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: unknown;
            }[];
            /** Calculator Results */
            calculator_results: {
                [key: string]: unknown;
            };
            /** Manual Inputs */
            manual_inputs: {
                [key: string]: unknown;
            };
            /**
             * Rule Version
             * @default 1
             */
            rule_version: number;
            /** Email Output */
            email_output?: string | null;
            /**
             * Period
             * @default
             */
            period: string;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
        };
        /**
         * SaveEvaluationResponse
         * @description Response after successfully saving an evaluation.
         */
        SaveEvaluationResponse: {
            /** Id */
            id: number;
            /** Brand Id */
            brand_id: number;
            /** Final Score */
            final_score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Period
             * @default
             */
            period: string;
        };
        /**
         * ScoringRequest
         * @description Request body for generating a final score.
         */
        ScoringRequest: {
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /**
             * Store Name
             * @default
             */
            store_name: string;
            /**
             * Period
             * @default
             */
            period: string;
            /**
             * Brand Name
             * @default
             */
            brand_name: string;
            /** Email */
            email?: string | null;
        };
        /**
         * ScoringResponse
         * @description Response for scoring endpoint — complete scoring result.
         */
        ScoringResponse: {
            /** Total Score */
            total_score: number;
            /** Category Scores */
            category_scores: components["schemas"]["CategoryScoreItem"][];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "✔️" | "❌" | "❌ Non Mall" | "❌ No Brand" | "❌ Opex" | "❌ Stock";
            /** Conclusion */
            conclusion: string;
            /** Marketing Estimation */
            marketing_estimation: string;
            /** Marketing Percentage */
            marketing_percentage: string;
            /** Marketing Budget */
            marketing_budget: string;
            /** Closing Message */
            closing_message: string;
            /** Email Subject */
            email_subject: string;
            /** Email Body */
            email_body: string;
            /**
             * Template
             * @enum {string}
             */
            template: "fashion" | "non_fashion";
            /** Rule Version */
            rule_version: number;
            /** Conclusion I18N */
            conclusion_i18n?: components["schemas"]["TranslatableTextSchema"][] | null;
            marketing_budget_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
            closing_message_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
            email_subject_i18n?: components["schemas"]["TranslatableTextSchema"] | null;
        };
        /**
         * ScoringRuleResponse
         * @description Scoring rule response matching the scoring_rules table.
         */
        ScoringRuleResponse: {
            /** Id */
            id: number;
            /** Template */
            template: string;
            /**
             * Marketplace
             * @default ID
             */
            marketplace: string;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /** Updated By */
            updated_by?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScoringRuleUpdateRequest
         * @description Request body for updating scoring rules.
         */
        ScoringRuleUpdateRequest: {
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
        };
        /**
         * SendEmailRequest
         * @description Request body for sending an evaluation email.
         */
        SendEmailRequest: {
            /** Evaluation Id */
            evaluation_id: number;
            /** Recipients */
            recipients: string[];
            /** Cc */
            cc?: string[];
            /** Bcc */
            bcc?: string[];
            /**
             * Chart Image
             * @description Base64-encoded PNG chart image (optional — placeholder used if empty)
             * @default
             */
            chart_image: string;
            /** Subject */
            subject?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Language
             * @default id
             */
            language: string;
        };
        /**
         * SendEmailResponse
         * @description Response after sending (or previewing) an email.
         */
        SendEmailResponse: {
            /** Success */
            success: boolean;
            /** Message Id */
            message_id: string;
            /** Recipients */
            recipients: string[];
        };
        /**
         * SendGridWebhookEvent
         * @description Single SendGrid Event Webhook payload.
         */
        SendGridWebhookEvent: {
            /** Event */
            event: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Sg Message Id
             * @default
             */
            sg_message_id: string;
            /**
             * Timestamp
             * @default 0
             */
            timestamp: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Type
             * @default
             */
            type: string;
        };
        /** SignedUrlRequest */
        SignedUrlRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** File Type */
            file_type: string;
            /** Brand Id */
            brand_id: number;
        };
        /** SignedUrlResponse */
        SignedUrlResponse: {
            /** Upload Url */
            upload_url: string;
            /** Upload Id */
            upload_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * SingleCalculatorStatus
         * @description Readiness status for a single calculator.
         */
        SingleCalculatorStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "pending";
            /** Has Result */
            has_result: boolean;
            /** Required Files */
            required_files: string[];
            /**
             * Required Manual
             * @default []
             */
            required_manual: string[];
            /** Available Files */
            available_files: string[];
            /** Missing Files */
            missing_files: string[];
            /**
             * Missing Manual
             * @default []
             */
            missing_manual: string[];
            /** Calculated At */
            calculated_at?: string | null;
        };
        /**
         * SyncDetailResponse
         * @description Per-sheet detail persisted in sync_details JSON.
         */
        SyncDetailResponse: {
            /** Status */
            status: string;
            /** Rows Synced */
            rows_synced?: number | null;
            /** Rows Skipped */
            rows_skipped?: number | null;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[] | null;
            /** Error */
            error?: string | null;
            /** Marketplace */
            marketplace?: string | null;
            /** Sheet */
            sheet?: string | null;
            /** Expected Headers */
            expected_headers?: string[] | null;
            /** Actual Headers */
            actual_headers?: string[] | null;
            /** Missing */
            missing?: string[] | null;
            /** Unexpected */
            unexpected?: string[] | null;
            /** Changed Columns */
            changed_columns?: components["schemas"]["ColumnChangeDetail"][] | null;
        };
        /**
         * SyncStatusResponse
         * @description Response model for sync status endpoint.
         */
        SyncStatusResponse: {
            /** Id */
            id: number;
            /**
             * Last Sync
             * Format: date-time
             */
            last_sync: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "failed" | "in_progress";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Brands Synced */
            brands_synced: number;
            /** Error Message */
            error_message: string | null;
            /** Sync Details */
            sync_details?: {
                [key: string]: components["schemas"]["SyncDetailResponse"];
            } | null;
        };
        /**
         * TranslatableTextSchema
         * @description i18n structured data for frontend translation.
         */
        TranslatableTextSchema: {
            /** Key */
            key: string;
            /**
             * Vars
             * @default {}
             */
            vars: {
                [key: string]: string;
            };
        };
        /**
         * UpdateLanguageRequest
         * @description Request body for updating language preference.
         */
        UpdateLanguageRequest: {
            /**
             * Language
             * @enum {string}
             */
            language: "id" | "en" | "th";
        };
        /**
         * UpdateRoleRequest
         * @description Request body for updating a user's role.
         */
        UpdateRoleRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "member" | "leader" | "admin";
        };
        /** UploadResponse */
        UploadResponse: {
            /** Id */
            id: number;
            /** Brand Id */
            brand_id: number;
            /** File Type */
            file_type: string;
            /** Filename */
            filename: string;
            /** File Size */
            file_size: number;
            /** Row Count */
            row_count: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * UserListResponse
         * @description Single user in the accounts list.
         */
        UserListResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Language
             * @default id
             */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login */
            last_login?: string | null;
        };
        /**
         * UserResponse
         * @description Response schema for authenticated user info.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Language
             * @default id
             */
            language: string;
            /** Last Login */
            last_login: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_endpoint_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"][];
                };
            };
        };
    };
    create_account_endpoint_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_endpoint_api_v1_accounts__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_endpoint_api_v1_accounts__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_endpoint_api_v1_accounts__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_language_api_v1_me_language_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLanguageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brands_api_v1_brands_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Search by brand name */
                search?: string | null;
                /** @description Comma-separated marketplace filter (e.g., 'ID,TH') */
                marketplace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_api_v1_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_api_v1_config_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    list_history_endpoint_api_v1_email_history_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sort_by?: string;
                sort_order?: string;
                search?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailHistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_endpoint_api_v1_email_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteEmailHistoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEmailHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_history_endpoint_api_v1_email_history__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_email_endpoint_api_v1_email_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendEmailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_email_endpoint_api_v1_email_preview__evaluation_id__get: {
        parameters: {
            query?: {
                note?: string | null;
                language?: string | null;
            };
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_endpoint_api_v1_evaluations_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sort_by?: "created_at" | "final_score";
                sort_order?: "asc" | "desc";
                search?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grouped_evaluations_endpoint_api_v1_evaluations_grouped_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                /** @description Comma-separated marketplace filter (e.g., 'ID,TH') */
                marketplace?: string | null;
                /** @description Comma-separated grouped verdict filter (approved,non_approved) */
                verdict?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupedEvaluationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brand_evaluations_endpoint_api_v1_evaluations_grouped__brand_id__get: {
        parameters: {
            query?: {
                limit?: number | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandEvaluationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_detail_endpoint_api_v1_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evaluation_endpoint_api_v1_evaluations__evaluation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_v1_evaluations_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_evaluation_api_v1_evaluations_brands__brand_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationInputsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calculator_results_api_v1_evaluations_brands__brand_id__calculators_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResultsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ads_keyword_calculator_api_v1_evaluations_brands__brand_id__calculators_ads_keyword_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_discount_calculator_api_v1_evaluations_brands__brand_id__calculators_discount_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_top_sku_calculator_api_v1_evaluations_brands__brand_id__calculators_top_sku_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_calculators_api_v1_evaluations_brands__brand_id__calculators_run_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAllResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calculator_status_api_v1_evaluations_brands__brand_id__calculators_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_evaluation_api_v1_evaluations_brands__brand_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_evaluation_endpoint_api_v1_evaluations_brands__brand_id__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: {
                /** @description Marketplace code (ID or TH) */
                marketplace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rules_endpoint_api_v1_rules__template__put: {
        parameters: {
            query?: {
                /** @description Marketplace code (ID or TH) */
                marketplace?: string;
            };
            header?: never;
            path: {
                template: "fashion" | "non_fashion" | "default";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_v1_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    sync_eval_sheet_api_v1_sync_eval_sheet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSheetSyncResponse"];
                };
            };
        };
    };
    get_sync_status_api_v1_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"] | null;
                };
            };
        };
    };
    create_signed_url_api_v1_upload_signed_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignedUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_processing_api_v1_upload_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_uploads_api_v1_upload_brands__brand_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandUploadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_v1_upload_brands__brand_id__download__file_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: number;
                file_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_download_api_v1_upload_local__upload_id___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_upload_api_v1_upload_local__upload_id___filename__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sendgrid_webhook_api_v1_webhooks_sendgrid_post: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendGridWebhookEvent"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
